version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    ports:
      - "3306:3306"  # Map MySQL to host port 3306
    env_file:
      - /home/ryan/secure-directory/db-credentials/personal-website/.env  # MySQL environment variables
    volumes:
      - mysql_data:/var/lib/mysql  # MySQL data persistence
      - ./MySQL/website-schema.sql:/docker-entrypoint-initdb.d/website-schema.sql  # Schema setup
    networks:
      - backend

  backend:
    build:
      context: ./backend  # Path to backend directory
      dockerfile: Dockerfile
    container_name: backend-container
    restart: always
    ports:
      - "5000:5000"  # Map backend to host port 5000
    depends_on:
      - mysql  # Ensure MySQL starts before backend
    volumes:
      - ./backend:/app  # Mount backend code for development
      - /home/ryan/secure-directory/db-credentials/personal-website/.env:/app/.env  # Mount environment file
    networks:
      - backend

  frontend:
    build:
      context: ./frontend  # Path to frontend directory
      dockerfile: Dockerfile
    container_name: frontend-container
    restart: always
    ports:
      - "3000:80"  # Map frontend to host port 3000
    networks:
      - backend

  emulator:
    build:
      context: ./emulator  # Path to emulator directory
      dockerfile: Dockerfile.emulator
    container_name: emulator-container
    restart: always
    ports:
      - "8081:8081"  # Map emulator to host port 8081
    networks:
      - backend

volumes:
  mysql_data:  # MySQL data persistence

networks:
  backend:  # Shared network for all services
